name: Deploy Production

on:
  workflow_dispatch:

run-name: Deploy Production ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            TAG=${{ github.ref_name }}
            echo $TAG
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/projectsplit/splitserver:$TAG
            cd /home/user/split-production
            docker stop splitserver || true
            docker rm splitserver || true
            docker run -d \
              --name splitserver \
              -p 5097:5097 \
              -v $(pwd)/appsettings.Production.json:/app/appsettings.Production.json \
              -e ASPNETCORE_ENVIRONMENT=Production \
              --restart always \
              ghcr.io/projectsplit/splitserver:$TAG